version: '{build}'
skip_tags: true
image:
  - Visual Studio 2022
  - Ubuntu2204
configuration: Release
build_script:
- ps: ./Build.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - sh build.sh
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Aq5CDdWYP7KPB6TqJXn4Xs2ggxQtPFGb5YnDBZ+krxsSONVKr9sghxxi6PX5MnKL
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: ay9SXMQR5Xs9FJeuZdMGEkgAvl/vRA9TvLFv8Akx5LnHCkJ9n8AZeq6Lwxj11SXm7D522VuVMPz9eqq4vkoNjZBCDntZhGTHT8TgQ5hfOUw4qzo7NOih3wRNbfNHTb62
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
